stages:
  - validate

validate:
  stage: validate
  script:
    - ./scripts/validate.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"